ALTER TABLE users MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE shops MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE products MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE addresses MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE coupons MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE users ADD COLUMN email VARCHAR(128);
ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NOT NULL DEFAULT '$2y$10$MXx1mauaIEYu4AIh/7zR0.UvOWt2lMc1/ISi7bSHnf3IFFdiIgCce';
ALTER TABLE users ADD COLUMN avatar_url VARCHAR(255);
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP NULL;
ALTER TABLE users MODIFY COLUMN phone VARCHAR(32) NOT NULL;
ALTER TABLE users ADD UNIQUE INDEX uk_users_username (username);
ALTER TABLE users ADD UNIQUE INDEX uk_users_phone (phone);

ALTER TABLE shops ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'OPEN';
ALTER TABLE shops ADD COLUMN service_modes VARCHAR(128) NOT NULL DEFAULT 'DELIVERY';
ALTER TABLE shops ADD COLUMN min_order_amount DECIMAL(10,2) NOT NULL DEFAULT 20.00;

ALTER TABLE products ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE addresses ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE user_coupons ADD COLUMN claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE orders ADD COLUMN review_score INT NULL;
ALTER TABLE orders ADD COLUMN review_content VARCHAR(255) NULL;
ALTER TABLE orders ADD COLUMN reviewed_at TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS favorite_shops (
  user_id BIGINT NOT NULL,
  shop_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, shop_id)
);

CREATE TABLE IF NOT EXISTS search_history (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  keyword VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rider_profiles (
  user_id BIGINT PRIMARY KEY,
  online BOOLEAN NOT NULL DEFAULT TRUE,
  capacity INT NOT NULL DEFAULT 3,
  vehicle_type VARCHAR(64) NOT NULL DEFAULT '电动车'
);
