CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role VARCHAR(32) NOT NULL,
  username VARCHAR(64) NOT NULL UNIQUE,
  display_name VARCHAR(64) NOT NULL,
  phone VARCHAR(32) NOT NULL UNIQUE,
  email VARCHAR(128),
  password_hash VARCHAR(255) NOT NULL,
  level VARCHAR(32),
  shop_id BIGINT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  avatar_url VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS shops (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  merchant_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  score DECIMAL(3,2) NOT NULL DEFAULT 4.50,
  monthly_sales INT NOT NULL DEFAULT 0,
  delivery_fee DECIMAL(10,2) NOT NULL,
  delivery_minutes INT NOT NULL,
  average_price DECIMAL(10,2) NOT NULL,
  distance_km DOUBLE NOT NULL DEFAULT 1.0,
  tags VARCHAR(255),
  announcement VARCHAR(255),
  status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  service_modes VARCHAR(128) NOT NULL DEFAULT 'DELIVERY',
  min_order_amount DECIMAL(10,2) NOT NULL DEFAULT 20.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  shop_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  original_price DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL,
  monthly_sales INT NOT NULL DEFAULT 0,
  description VARCHAR(255),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS addresses (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  label VARCHAR(32) NOT NULL,
  detail VARCHAR(255) NOT NULL,
  contact_name VARCHAR(64) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  scope VARCHAR(32) NOT NULL,
  title VARCHAR(128) NOT NULL,
  description VARCHAR(255),
  discount_amount DECIMAL(10,2) NOT NULL,
  minimum_spend DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL,
  valid_until TIMESTAMP NOT NULL,
  shop_id BIGINT NULL
);

CREATE TABLE IF NOT EXISTS user_coupons (
  user_id BIGINT NOT NULL,
  coupon_id BIGINT NOT NULL,
  claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, coupon_id)
);

CREATE TABLE IF NOT EXISTS member_profiles (
  user_id BIGINT PRIMARY KEY,
  level VARCHAR(32) NOT NULL,
  growth_points INT NOT NULL,
  reward_points INT NOT NULL,
  benefits_text TEXT NOT NULL,
  tasks_text TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS carts (
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INT NOT NULL,
  PRIMARY KEY (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  shop_id BIGINT NOT NULL,
  rider_id BIGINT NULL,
  status VARCHAR(64) NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  payable_amount DECIMAL(10,2) NOT NULL,
  coupon_id BIGINT NULL,
  address_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  review_score INT NULL,
  review_content VARCHAR(255) NULL,
  reviewed_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  product_name VARCHAR(128) NOT NULL,
  quantity INT NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_status_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  status VARCHAR(64) NOT NULL,
  note VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  scene VARCHAR(32) NOT NULL,
  order_id BIGINT NULL,
  title VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_participants (
  conversation_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  user_role VARCHAR(32) NOT NULL,
  PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  conversation_id BIGINT NOT NULL,
  sender_id BIGINT NOT NULL,
  sender_role VARCHAR(32) NOT NULL,
  message_type VARCHAR(32) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  config_group VARCHAR(64) NOT NULL,
  config_key VARCHAR(64) NOT NULL,
  config_value VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS favorite_shops (
  user_id BIGINT NOT NULL,
  shop_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, shop_id)
);

CREATE TABLE IF NOT EXISTS search_history (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  keyword VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rider_profiles (
  user_id BIGINT PRIMARY KEY,
  online BOOLEAN NOT NULL DEFAULT TRUE,
  capacity INT NOT NULL DEFAULT 3,
  vehicle_type VARCHAR(64) NOT NULL DEFAULT '电动车'
);

-- Align legacy databases created by older MVP builds with the V2 runtime expectations.
ALTER TABLE users MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE shops MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE products MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE addresses MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE coupons MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE users ADD COLUMN email VARCHAR(128);
ALTER TABLE users ADD COLUMN password_hash VARCHAR(255) NOT NULL DEFAULT '$2y$10$MXx1mauaIEYu4AIh/7zR0.UvOWt2lMc1/ISi7bSHnf3IFFdiIgCce';
ALTER TABLE users ADD COLUMN avatar_url VARCHAR(255);
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP NULL;
ALTER TABLE users MODIFY COLUMN phone VARCHAR(32) NOT NULL;
ALTER TABLE users ADD UNIQUE INDEX uk_users_username (username);
ALTER TABLE users ADD UNIQUE INDEX uk_users_phone (phone);

ALTER TABLE shops ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'OPEN';
ALTER TABLE shops ADD COLUMN service_modes VARCHAR(128) NOT NULL DEFAULT 'DELIVERY';
ALTER TABLE shops ADD COLUMN min_order_amount DECIMAL(10,2) NOT NULL DEFAULT 20.00;

ALTER TABLE products ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE addresses ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE user_coupons ADD COLUMN claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE orders ADD COLUMN review_score INT NULL;
ALTER TABLE orders ADD COLUMN review_content VARCHAR(255) NULL;
ALTER TABLE orders ADD COLUMN reviewed_at TIMESTAMP NULL;
